### PR TITLE
New people page

### PR DESCRIPTION
**Pull request by catsarebetter98**
**Adding new people page and adding footer. Works on mobile too.**

Screen Shot 2022-02-23 at 11 14 45 PM
Screen Shot 2022-02-23 at 11 14 55 PM
Screen Shot 2022-02-23 at 11 17 21 PM

**New Profile Page**
Screen Shot 2022-02-23 at 11 41 42 PM
Screen Shot 2022-02-23 at 11 41 33 PM

**Landing Page in Progress**
TODO: Text needs to be decided, need @jlevy44 for this.
Screen Shot 2022-02-24 at 11 11 12 PM
Screen Shot 2022-02-24 at 11 11 18 PM
49bc0bb3189.png">
Screen Shot 2022-02-24 at 11 11 25 PM

^^ I would recommend using a calendly link here to schedule a zoom call - https://calendly.com/for-individuals, can help intro you to this or set this up for you

### CODE REVIEW

**Comment by jlevy44** [comment]
- [x] picsum, can you keep same random seed and cycle through when no profile picture
- [x]  Want to join the lab from red to Dartmouth green
- [x] google drive, maybe adding a direct link if iframe not working properly
- [x] separate out current and former students
- [x] correctly categorize students

**Comment by jlevy44** [comment]
Then I'll approve PR, add new text and build locally, then will deploy

**Comment by jlevy44** [comment]
- make project page clicks look like people
- refactor application
- add abstract, links and code to publications (low priority)
- software, teaching
- software pulls info from jlevy44 github

**Comment by jlevy44** [comment]
- software mirrors github page

**Comment by catsarebetter98** [comment]
@jlevy44 

- google drive, maybe adding a direct link if iframe not working properly
Fix is here https://github.com/jlevy44/levylab/pull/2

**Comment by catsarebetter98** [comment]
- Want to join the lab from red to Dartmouth green
Screen Shot 2022-02-28 at 10 33 08 PM

**Comment by catsarebetter98** [comment]
- picsum, can you keep same random seed and cycle through when no profile picture

Not using lorem picsum anymore, faster implementation, solves problem the same way. Industry standard is to use a blank profile pic, also saves api call so speeds up load time of page.

Screen Shot 2022-03-01 at 9 58 15 PM

**Comment by jlevy44** [comment]
You're the best! I will review. Any recommendations for the opportunities page?

**Comment by catsarebetter98** [comment]
Lol I think a redesign of the page, more concise text and large CTAs to quickly direct students to apply

**Comment by catsarebetter98** [comment]
Bit of a personal design decision, let me know if this isn't what you're looking for @jlevy44 

-  separate out current and former students
-  correctly categorize students

Screen Shot 2022-03-04 at 11 39 33 AM
Screen Shot 2022-03-04 at 11 47 09 AM

**Comment by jlevy44** [comment]
Thanks @catsarebetter98 I will pull and run locally and may push to this PR a few changes prior to merge with Master.

**Comment by jlevy44** [comment]
Re: calendly, I'm not sure I'm quite there yet :)

**Pull request merged**
